include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  nest:
    container_name: nest
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      kafka-topic-generator:
        condition: service_completed_successfully
