include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  nest:
    container_name: nest
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    depends_on:
      kafka-topic-generator:
        condition: service_completed_successfully
