services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/node/app
    ports:
      - 3001:3000
    depends_on:
      kafka-topic-generator:
        condition: service_completed_successfully
