include:
  - ../mongodb/docker-compose.yaml
  - ../kafka/docker-compose.yaml

services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
      kafka-topic-generator:
        condition: service_completed_successfully
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/routes?authSource=admin&directConnection=true
      - KAFKA_BROKER=kafka:9092
      - KAFKA_ROUTE_TOPIC=route
      - KAFKA_FREIGHT_TOPIC=freight
      - KAFKA_SIMULATION_TOPIC=simulation
      - KAFKA_GROUP_ID=route-group
